## -*- python -*-

##
# APPLICATION specific build data
##

# Include directories
incs = ['LAPACK']

# Libraries to link to
libs = []

# Library paths
libp = []

# Source files for this APPLICATION
sources = ['flux.cc',
           'setprob.cc',
           'rp3eu.cc',
           'rp_lax.cc',
           'src.cc',
           'rkdg_euler_limiter.cc',
           'before_step.cc',
           'maxs.cc',
           'bc.cc',
           'out.cc',
           'LAPACK/blas_lite.c',
           'LAPACK/dlapack_lite.c',
           'LAPACK/f2c_lite.c'
           ]

##
# You should not need to modify anything below this line
##

# find $MINIWARPX environment variable
import os.path
MINIWARPX = os.path.expandvars('$MINIWARPX')

# construct a new build environment
env = Environment()

# set WarpX INCLUDE directories
warpx_incs = [MINIWARPX + '/src/etc',
              MINIWARPX + '/src/lib']
env.Append(CPPPATH = incs + warpx_incs)

# read buildopts file to determine the build option
ccflags = open(MINIWARPX + "/src/buildopts").read()
env.Append(CCFLAGS = ccflags) # set options just read

# build the sources
objs = []
for s in sources:
    o = env.Object(s)
    objs.append(o)
